---
project_name: rabdis
before:
  hooks:
    - go mod download
    - go generate ./...
builds:
  - main: ./cmd/rabdis/main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ldflags:
      - -s -w -X github.com/julienbreux/rabdis/pkg/version.Version={{.Version}} -X github.com/julienbreux/rabdis/pkg/version.Commit={{.Commit}} -X github.com/julienbreux/rabdis/pkg/version.RawDate={{.Date}}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: checksums.txt
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
dockers:
  - image_templates:
      - 'julienbreux/rabdis:{{ .Tag }}-amd64'
      - 'ghcr.io/julienbreux/rabdis:{{ .Tag }}-amd64'
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --pull
      - --platform=linux/amd64
      - --label=org.opencontainers.image.name={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/julienbreux/rabdis
      - --label=org.opencontainers.image.source=https://github.com/julienbreux/rabdis
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
  - image_templates:
      - 'julienbreux/rabdis:{{ .Tag }}-arm64'
      - 'ghcr.io/julienbreux/rabdis:{{ .Tag }}-arm64'
    dockerfile: Dockerfile
    use_buildx: true
    build_flag_templates:
      - --pull
      - --platform=linux/arm64/v8
      - --label=org.opencontainers.image.name={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/julienbreux/rabdis
      - --label=org.opencontainers.image.source=https://github.com/julienbreux/rabdis
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.created={{ time "2006-01-02T15:04:05Z07:00" }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=Apache-2.0
docker_manifests:
  - name_template: 'ghcr.io/julienbreux/rabdis:{{ .Version }}'
    image_templates:
      - 'ghcr.io/julienbreux/rabdis:{{ .Version }}-amd64'
      - 'ghcr.io/julienbreux/rabdis:{{ .Version }}-arm64'
  - name_template: 'ghcr.io/julienbreux/rabdis:latest'
    image_templates:
      - 'ghcr.io/julienbreux/rabdis:{{ .Version }}-amd64'
      - 'ghcr.io/julienbreux/rabdis:{{ .Version }}-arm64'
  - name_template: 'julienbreux/rabdis:{{ .Tag }}'
    image_templates:
      - 'julienbreux/rabdis:{{ .Tag }}-amd64'
      - 'julienbreux/rabdis:{{ .Tag }}-arm64'
  - name_template: 'julienbreux/rabdis:latest'
    image_templates:
      - 'julienbreux/rabdis:{{ .Tag }}-amd64'
      - 'julienbreux/rabdis:{{ .Tag }}-arm64'
brews:
  - name: rabdis
    tap:
      owner: JulienBreux
      name: rabdis-homebrew
    commit_author:
      name: Julien Breux
      email: julien@golang.fr
    folder: Formula
    homepage: https://github.com/julienbreux/rabdis/
    description: 🐰 Rabdis – Play with redis keys from RabbitMQ messages
    test: system "rabdis version"
