apiVersion: apps/v1
kind: ConfigMap
metadata:
  name: {{ include "rabdis.fullname" . }}
  labels:
    {{- include "rabdis.labels" . | nindent 4 }}
data:
  rabdis.yaml: |
    ---
    version: 1

    {{- with .Values.rules }}
    rules:
      {{- toYaml . | nindent 2 }}
    {{- end }}
