apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabdis.fullname" . }}
  labels:
    {{- include "rabdis.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rabdis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "rabdis.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "rabdis.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: HOST_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: RABDIS_CONFIG_FILE
              value: /config/rabdis.yaml
            - name: RABBITMQ_HOST
              value: {{ .Values.rabbitmq.host | squote }}
            - name: RABBITMQ_PORT
              value: {{ .Values.rabbitmq.port | squote }}
            - name: RABBITMQ_USER
              value: {{ .Values.rabbitmq.user | squote }}
            - name: RABBITMQ_CONN_TIMEOUT
              value: {{ .Values.rabbitmq.connTimeout | squote }}
            - name: REDIS_HOST
              value: {{ .Values.redis.host | squote }}
            - name: REDIS_PORT
              value: {{ .Values.redis.port | squote }}
            - name: REDIS_DATABASE
              value: {{ .Values.redis.database | squote }}
            - name: REDIS_PING_DELAY
              value: {{ .Values.redis.pingDelay | squote }}
            - name: REDIS_KEY_PREFIX
              value: {{ .Values.redis.keyPrefix | squote }}
          envFrom:
            - secretRef:
                name: {{ include "rabdis.fullname" . }}
          ports:
            - name: http-health
              containerPort: 8181
            - name: http-metrics
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http-health
          readinessProbe:
            httpGet:
              path: /health
              port: http-health
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ include "rabdis.fullname" . }}
              mountPath: /config/rabdis.yaml
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
