apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rabdis.fullname" . }}
  labels:
    {{- include "rabdis.labels" . | nindent 4 }}
type: Opaque
stringData:
  RABBITMQ_PASSWORD: {{ .Values.rabbitmq.password | squote }}
  REDIS_PASSWORD: {{ .Values.redis.password | squote }}
