apiVersion: v1
kind: Service
metadata:
  name: {{ include "rabdis.fullname" . }}
  labels:
    {{- include "rabdis.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.health }}
      targetPort: http-health
      protocol: TCP
      name: http-health
    - port: {{ .Values.service.ports.metrics }}
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "rabdis.selectorLabels" . | nindent 4 }}
