{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "rabdis.fullname" . }}
  labels:
    {{- include "rabdis.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "rabdis.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http-metrics
{{- end }}
